apiVersion: apps/v1
kind: Deployment
metadata:
  name: goa-deployment
  labels:
    app: map-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-server
  template:
    metadata:
      labels:
        app: map-server
    spec:
      containers:
      - name: map-server
        image: goa/map-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: goa-service
# spec:
#   selector:
#     app: map-server
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer
